module.exports = {
  //For Proposals:
  PROPOSAL_ACCEPTED: 1,
  PROPOSAL_PENDING: 0,
  PROPOSAL_REJECTED: 2,

  //For Tasks:
  TASK_PENDING: 0,
  TASK_COMPLETED: 1,
  TASK_PAUSED: 2,
  TASK_ARCHIVED: 3,
  TASK_ASSIGNED: 4,
};
